/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'lehenga' : IDL.Null,
  'jewellery' : IDL.Null,
  'sarees' : IDL.Null,
  'westernDresses' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'product' : Product,
});
export const ContactInfo = IDL.Record({
  'businessHours' : IDL.Text,
  'physicalAddress' : IDL.Text,
  'emailAddress' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const HeroSection = IDL.Record({
  'backgroundImageUrl' : IDL.Text,
  'headline' : IDL.Text,
  'description' : IDL.Text,
});
export const SocialMediaLinks = IDL.Record({
  'whatsappUrl' : IDL.Text,
  'instagramUrl' : IDL.Text,
  'facebookUrl' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'date' : IDL.Text,
  'reviewText' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, Category],
      [],
      [],
    ),
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateTotal' : IDL.Func([], [IDL.Nat], ['query']),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getHeroSection' : IDL.Func([], [HeroSection], ['query']),
  'getProducts' : IDL.Func([IDL.Opt(Category)], [IDL.Vec(Product)], ['query']),
  'getSocialMediaLinks' : IDL.Func([], [SocialMediaLinks], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeCartItem' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateContactInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateHeroSection' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, Category],
      [],
      [],
    ),
  'updateSocialMediaLinks' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTestimonial' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'lehenga' : IDL.Null,
    'jewellery' : IDL.Null,
    'sarees' : IDL.Null,
    'westernDresses' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'product' : Product });
  const ContactInfo = IDL.Record({
    'businessHours' : IDL.Text,
    'physicalAddress' : IDL.Text,
    'emailAddress' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const HeroSection = IDL.Record({
    'backgroundImageUrl' : IDL.Text,
    'headline' : IDL.Text,
    'description' : IDL.Text,
  });
  const SocialMediaLinks = IDL.Record({
    'whatsappUrl' : IDL.Text,
    'instagramUrl' : IDL.Text,
    'facebookUrl' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'date' : IDL.Text,
    'reviewText' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, Category],
        [],
        [],
      ),
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateTotal' : IDL.Func([], [IDL.Nat], ['query']),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getHeroSection' : IDL.Func([], [HeroSection], ['query']),
    'getProducts' : IDL.Func(
        [IDL.Opt(Category)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getSocialMediaLinks' : IDL.Func([], [SocialMediaLinks], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeCartItem' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateContactInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateHeroSection' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, Category],
        [],
        [],
      ),
    'updateSocialMediaLinks' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTestimonial' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };