/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'quantity' : bigint, 'product' : Product }
export type Category = { 'lehenga' : null } |
  { 'jewellery' : null } |
  { 'sarees' : null } |
  { 'westernDresses' : null };
export interface ContactInfo {
  'businessHours' : string,
  'physicalAddress' : string,
  'emailAddress' : string,
  'phoneNumber' : string,
}
export interface HeroSection {
  'backgroundImageUrl' : string,
  'headline' : string,
  'description' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export interface SocialMediaLinks {
  'whatsappUrl' : string,
  'instagramUrl' : string,
  'facebookUrl' : string,
}
export interface Testimonial {
  'id' : bigint,
  'customerName' : string,
  'date' : string,
  'reviewText' : string,
  'rating' : bigint,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, bigint, string, Category],
    undefined
  >,
  'addTestimonial' : ActorMethod<[string, bigint, string, string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateTotal' : ActorMethod<[], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getHeroSection' : ActorMethod<[], HeroSection>,
  'getProducts' : ActorMethod<[[] | [Category]], Array<Product>>,
  'getSocialMediaLinks' : ActorMethod<[], SocialMediaLinks>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeCartItem' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCartItem' : ActorMethod<[bigint, bigint], undefined>,
  'updateContactInfo' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateHeroSection' : ActorMethod<[string, string, string], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, string, Category],
    undefined
  >,
  'updateSocialMediaLinks' : ActorMethod<[string, string, string], undefined>,
  'updateTestimonial' : ActorMethod<
    [bigint, string, bigint, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];